# Generated by Django 4.0.2 on 2022-02-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidUptoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Father_Name', models.CharField(max_length=30)),
                ('Roll_No', models.IntegerField()),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.department')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.semester')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='Valid_Upto_Date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.validuptodate'),
        ),
    ]
